### ISSUE TITLE
f37-backgrounds-37.0.4 installs broken symlinks

### ISSUE THREAD

**Issue by pacho2** [fedoradesign/backgrounds#45] opened 2022-12-04 14:09 UTC
It installs broken links for files under /usr/share/wallpapers/F37_light-blue/contents/images/:
```
lrwxrwxrwx 1 root root 49 oct 22 23:37 1024x600.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1024x768.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1152x720.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1152x864.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1200x900.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1280x1024.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1280x720.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1280x768.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1280x800.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1280x960.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1366x768.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1440x1080.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1440x900.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1600x1200.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1600x1280.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1680x1050.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1920x1080.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1920x1200.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 1920x1440.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 2048x1536.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 2160x1440.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 2304x1440.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 2560x1440.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 2560x1600.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 2960x1440.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 3000x2000.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 3200x1800.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 3440x1440.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 3840x2160.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 640x480.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 800x480.png -> ../../../../backgrounds/f37/extras/light-blue.png
lrwxrwxrwx 1 root root 49 oct 22 23:37 800x600.png -> ../../../../backgrounds/f37/extras/light-blue.png
```

_Originally posted by @pacho2 in https://github.com/fedoradesign/backgrounds/issues/43#issuecomment-1287926300_

**Comment by luyatshimbalanga** [comment] 2023-03-16 00:15
Hello pacho2, sorry for the delay. The root cause is the missing light blue wallpaper on the extras sub-folder. The issue is resolved with the release of 37.0.5

**Closed as completed by luyatshimbalanga** 2023-03-16 00:15 UTC
Labels: bug
